trigger:
- main

pool:
  name: infra-pool 

steps:
- script: |
    sudo apt-get update -y
    sudo apt-get install -y wget unzip
    wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    unzip terraform_1.6.6_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: Install Terraform

- script: |
    cd infra
    terraform init
  displayName: Terraform Init

- script: |
    cd infra
    terraform validate
  displayName: Terraform Validate

- script: |
    cd infra
    terraform fmt -check
  displayName: Terraform Lint (fmt)

- script: |
    cd infra
    curl -L https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
    chmod +x tfsec
    ./tfsec .
  displayName: Terraform Security Scan (tfsec)

- script: |
    cd infra
    terraform plan
  displayName: Terraform Plan

- script: |
    cd infra
    terraform apply -auto-approve
  displayName: Terraform Apply
