trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: "1.6.6"

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

- script: terraform init
  displayName: Terraform Init

- script: terraform validate
  displayName: Terraform Validate

- script: terraform fmt -check
  displayName: Terraform Lint (fmt)

- script: |
    curl -L https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
    chmod +x tfsec
    ./tfsec .
  displayName: Terraform Security Scan (tfsec)

- script: terraform plan -out=tfplan
  displayName: Terraform Plan

- script: terraform apply -auto-approve tfplan
  displayName: Terraform Apply
